controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# login:
#     path: /login
#     controller: App\Controller\AuthhhhhController::loginAction